# Generated by Django 5.2.8 on 2025-11-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('image', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
