# Generated by Django 5.2.8 on 2025-11-30 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
