# Generated by Django 5.2.8 on 2025-12-06 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectronicDeal',
            new_name='ElectronicsDeal',
        ),
    ]
