# Generated by Django 5.2.8 on 2025-12-06 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('store', models.CharField(blank=True, max_length=255, null=True)),
                ('price_old', models.FloatField(blank=True, null=True)),
                ('price_new', models.FloatField()),
                ('url', models.URLField(unique=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
